name: Man10Bank
version: 1.0
auther: [forest611]
softdepend:
  - Vault
  - Man10CommonLibs
  - Man10Mail
  - Essentials
main: red.man10.man10bank.Man10Bank
api-version: 1.16
commands:
#  mbal:
#    default: op
  bal:
    default: op
  balance:
    default: op
  money:
    default: op
  bank:
    default: op
  mpay:
    default: op
  mbaltop:
    default: op
  mlend:
    default: op
  pay:
    default: op
  atm:
    default: op
  deposit:
    default: op
  withdraw:
    default: op
  mchequeop:
    default: op