name: 'Man10Bank'
version: '1.0'
main: red.man10.man10bank.Man10Bank
api-version: 1.19
softdepend:
  - Vault
  - Man10CommonLibs
commands:
  mcheque:
    description: '小切手を発行するコマンド'
  mchequeop:
    description: '小切手を発行するコマンド(OP)'
  atm:
    description: 'ATM'
  bal:
    description: 'balコマンド'
  balance:
    description: 'balコマンド'
  money:
    description: 'balコマンド'
  bank:
    description: 'balコマンド'
  d:
    description: '電子マネー->銀行'
  w:
    description: '銀行->電子マネー'
  deposit:
    description: '電子マネー->銀行'
  withdraw:
    description: '銀行->電子マネー'
  mrevo:
    description: 'リボのコマンド'